using TListPlugin; 
[System.Serializable]
public class GetDataSO_KeyStorageSelectProductId : Abs_Get_SO_IdentifierAndData<SO_Data_KeyStorageSelectProductId,IdentifierAndData_KeyStorageSelectProductId, IndifNameSO_KeyStorageSelectProductId, string, KeyStorageSelectProductId>
{

}
